export interface EducationalEntry {
    title: string;
    description: string;
    scientificContext: string;
    gameSignificance: string;
}

export const LEVER_INFO: Record<string, EducationalEntry> = {
    metabolism: {
        title: "Metabolic Rate",
        description: "The speed at which an organism converts resources into energy and cellular structure.",
        scientificContext: "In biology, metabolism represents the set of life-sustaining chemical reactions. A higher metabolic rate (like in warm-blooded animals) allows for faster growth and activity but requires significantly more energy (food). This is the 'Cost of Living'.",
        gameSignificance: "Higher settings accelerate Population Growth significantly but drastically increase Biomass Consumption. Risk of Starvation increases."
    },
    aggression: {
        title: "Interspecific Competition",
        description: "The tendency to compete with other organisms for niche dominance and resources.",
        scientificContext: "Aggression in evolutionary game theory often relates to the 'Hawk-Dove' strategy. 'Hawks' fight for resources, securing more land (carrying capacity) but risking injury. Dominant species secure more territory.",
        gameSignificance: "Increases your Maximum Carrying Capacity (Population Cap) through conquest, allowing for a larger empire. Future eras: increases risk of war."
    },
    adaptability: {
        title: "Phenotypic Plasticity",
        description: "The ability of an organism to change in response to stimuli or inputs from the environment.",
        scientificContext: "Species that are highly adaptable (generalists) can survive a wider range of environmental conditions (temperature, pH, salinity). While they may not be as efficient as specialists in a perfect environment, they are far more resilient to change.",
        gameSignificance: "Reduces the death rate during Crisis events (e.g., Ice Ages). Essential for survival when the environment turns hostile."
    },
    intellect: {
        title: "Encephalization",
        description: "The evolutionary increase in the complexity or relative size of the brain.",
        scientificContext: "Brains are metabolically expensive tissues. Developing intelligence requires a massive investment of evolutionary resources but unlocks tool use, problem-solving, and eventually, civilization. It is a high-risk, high-reward strategy.",
        gameSignificance: "Generates DNA (Research Points) needed to unlock the next Era. However, high intellect in later eras attracts 'The Great Filters' (AI rebellion, etc.)."
    },
    population: {
        title: "Population Dynamics",
        description: "The number of individuals in your species.",
        scientificContext: "Populations grow exponentially when resources are abundant but are limited by 'Carrying Capacity' (K). This follows the Logistic Growth model. Exceeding K leads to starvation and collapse.",
        gameSignificance: "Your score and workforce. More population means more DNA generation but exponentially higher Food consumption."
    },
    biomass: {
        title: "Biomass / Energy",
        description: "The raw biological material and energy available for growth.",
        scientificContext: "In ecology, biomass is the mass of living biological organisms in a given area. It represents the available energy (ATP) for reproduction and maintenance. If energy intake < expenditure, organisms die.",
        gameSignificance: "The fuel for Population growth. If this hits 0, your population will starve and die off rapidly."
    },
    dna: {
        title: "Genetic Information (DNA)",
        description: "The accumulated biological complexity and potential for mutation.",
        scientificContext: "Deoxyribonucleic acid (DNA) carries the genetic instructions for development, functioning, growth, and reproduction. 'Points' here represent beneficial mutations and evolutionary adaptations.",
        gameSignificance: "The currency for buying Evolutionary Upgrades (Techs) in Era 1."
    },
    knowledge: {
        title: "Accumulated Knowledge",
        description: "Abstract information, culture, and scientific understanding.",
        scientificContext: "As species evolve consciousness, genetic evolution is outpaced by memetic evolution (cultural transmission). Knowledge allows species to manipulate their environment rather than just adapting to it.",
        gameSignificance: "The currency for Era 2 technologies. Generated by Intelligent Population."
    }
};
